### ISSUE TITLE
Incorrect BW speeds

### ISSUE THREAD

**Issue by danmed** [vortex-5/ddwrt-bwmon#39] opened 2016-09-30 19:33 UTC
On recent firmwares, the speed in your script does not seem to be being reported correctly..

it seems to be reporting about a quarter of the speed that is actually being used.

**Comment by vortex-5** [comment] 2016-09-30 19:38
The last working DDWRT firmware is 30534 I'm waiting for them to resolve a bug in lighttpd before I can fix anything further there is an issue on their tracker.

Also if you are in lighttpd mode then the speeds will "catch up" to the actual speeds after 6 seconds after first startup this is a smoothing feature since without the smoothing the bandwidth speeds would spike too frequently to be readable.

As for non lighttpd versions I don't know what the BW discrepency is like since 30534 causes the lighttpd server to always deliver 500 errors so I'm waiting for that to be resolved before I can fix anything else.

**Comment by danmed** [comment] 2016-09-30 19:51
Thanks for the explanation.. i'm not in lighttpd mode. I have gone back to 30534 to see if things improve.

**Comment by vortex-5** [comment] 2016-09-30 19:53
http://svn.dd-wrt.com/ticket/5573

**Comment by gstrauss** [comment] 2017-01-05 10:20
@vortex-5: You updated http://svn.dd-wrt.com/ticket/5573 that this is working again.  If you're still waiting on something to be fixed in lighttpd, please update with more details.  Thx.

**Comment by danmed** [comment] 2017-01-05 14:42
If anyone cares, i've just bumped from 30534 to 30949 and this problem still exists..I'm downloading at 660KiB/s and BWMon is reporting between 70 and 120KB/s

**Comment by vortex-5** [comment] 2017-01-05 15:00
Not entirely sure where you're seeing Kibibyte because the rates are given in Kilobytes.

That said accurate measurement of download rates is partially dependent on how well your router can keep up with the logging. Are you using lighttpd or the user www method of accessing the information?

**Comment by danmed** [comment] 2017-01-05 15:34
I'm seeing KiB/s on syncthing.. the actual program that's download.. whereas your tool is reporting less than a quarter of that.. if i go back to 30534, then the numbers match.

**Comment by vortex-5** [comment] 2017-01-05 15:39
Could be a kong only thing I'll have to check if atheros units are affected.

**Comment by vortex-5** [comment] 2017-01-05 16:13
I'm unable to reproduce this I just did a test on my WNDR4300 running atheros and 30949

**Comment by danmed** [comment] 2017-01-05 16:22
I will test again once i am home later.

**Comment by vortex-5** [comment] 2017-01-05 16:24
Nothing has been updated code wise I'd expect the bug to still persist on your router however it's not something I can replicate.

**Closed** 2017-07-18 01:44 UTC
Labels: on hold
